targets:
  - "RZ-KSPW-DBI01"
  - "RZ-KSPW-DBT01"
  - "RZ-KSPW-DBT02"
  - "RZ-KSPW-DBT03"
  - "RZ-KSPW-DBT04"
  - "RZ-KSPW-DBT05"
  - "RZ-KSPW-DBT06"
  - "RZ-KSPW-DBT07"
  - "RZ-KSPW-DBT08"
  - "RZ-KSPW-DBT09"
  - "RZ-KSPW-DBT10"
  - "RZ-KSPW-DBX01"
  - "RZ-KSVW-DBE01"
  - "RZ-KSVW-DBR01"
  - "RZ-KSVW-DBR-D01"
  - "RZ-KSVW-DBV01"
  - "RZ-KSVW-DBW03"
  - "RZ-KSVW-DBW04"
  - "RZ-KSVW-DBW-T01"